package com.ampersand.ebanca.Model;
// Generated Aug 21, 2020 8:50:12 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "mibanco")
public class Area implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer idArea;
	private String nombreArea;
	private String cuenta;
	private List<Usuario> usuarios = new ArrayList<Usuario>(0);
	private List<Movimientos> movimientoses = new ArrayList<Movimientos>(0);
	private List<Presupuesto> presupuestos = new ArrayList<Presupuesto>(0);

	public Area() {
	}

	public Area(String nombreArea, String cuenta) {
		this.nombreArea = nombreArea;
		this.cuenta = cuenta;
	}

	public Area(String nombreArea, String cuenta, List<Usuario> usuarios, List<Movimientos> movimientoses,
			List<Presupuesto> presupuestos) {
		this.nombreArea = nombreArea;
		this.cuenta = cuenta;
		this.usuarios = usuarios;
		this.movimientoses = movimientoses;
		this.presupuestos = presupuestos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_area", unique = true, nullable = false)
	public Integer getIdArea() {
		return this.idArea;
	}

	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	@Column(name = "nombre_area", nullable = false, length = 70)
	public String getNombreArea() {
		return this.nombreArea;
	}

	public void setNombreArea(String nombreArea) {
		this.nombreArea = nombreArea;
	}

	@Column(name = "cuenta", nullable = false, length = 16)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public List<Movimientos> getMovimientoses() {
		return this.movimientoses;
	}

	public void setMovimientoses(List<Movimientos> movimientoses) {
		this.movimientoses = movimientoses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public List<Presupuesto> getPresupuestos() {
		return this.presupuestos;
	}

	public void setPresupuestos(List<Presupuesto> presupuestos) {
		this.presupuestos = presupuestos;
	}

}
