package com.ampersand.ebanca.Model;
// Generated Aug 21, 2020 8:50:12 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco", catalog = "mibanco")
public class Banco implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idBanco;
	private String nombreBanco;
	private List<Movimientos> movimientoses = new ArrayList<Movimientos>(0);

	public Banco() {
	}

	public Banco(String nombreBanco) {
		this.nombreBanco = nombreBanco;
	}

	public Banco(String nombreBanco, List<Movimientos> movimientoses) {
		this.nombreBanco = nombreBanco;
		this.movimientoses = movimientoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_banco", unique = true, nullable = false)
	public Integer getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(Integer idBanco) {
		this.idBanco = idBanco;
	}

	@Column(name = "nombre_banco", nullable = false, length = 70)
	public String getNombreBanco() {
		return this.nombreBanco;
	}

	public void setNombreBanco(String nombreBanco) {
		this.nombreBanco = nombreBanco;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "banco")
	public List<Movimientos> getMovimientoses() {
		return this.movimientoses;
	}

	public void setMovimientoses(List<Movimientos> movimientoses) {
		this.movimientoses = movimientoses;
	}

}
