package com.ampersand.ebanca.Model;
// Generated Aug 21, 2020 8:50:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comprobante generated by hbm2java
 */
@Entity
@Table(name = "comprobante", catalog = "mibanco")
public class Comprobante implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer idComprobante;
	private EstadoPresupuesto estadoPresupuesto;
	private String codigo;

	public Comprobante() {
	}

	public Comprobante(EstadoPresupuesto estadoPresupuesto, String codigo) {
		this.estadoPresupuesto = estadoPresupuesto;
		this.codigo = codigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_comprobante", unique = true, nullable = false)
	public Integer getIdComprobante() {
		return this.idComprobante;
	}

	public void setIdComprobante(Integer idComprobante) {
		this.idComprobante = idComprobante;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_estado_presupuesto", nullable = false)
	public EstadoPresupuesto getEstadoPresupuesto() {
		return this.estadoPresupuesto;
	}

	public void setEstadoPresupuesto(EstadoPresupuesto estadoPresupuesto) {
		this.estadoPresupuesto = estadoPresupuesto;
	}

	@Column(name = "codigo", nullable = false, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
