package com.ampersand.ebanca.Model;
// Generated Aug 21, 2020 8:50:12 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "mibanco")
public class Departamento implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer idDepartamento;
	private String nombreDepartamento;
	private String jefeDepartamento;
	private List<Presupuesto> presupuestos = new ArrayList<Presupuesto>(0);

	public Departamento() {
	}

	public Departamento(String nombreDepartamento, String jefeDepartamento) {
		this.nombreDepartamento = nombreDepartamento;
		this.jefeDepartamento = jefeDepartamento;
	}

	public Departamento(String nombreDepartamento, String jefeDepartamento, List<Presupuesto> presupuestos) {
		this.nombreDepartamento = nombreDepartamento;
		this.jefeDepartamento = jefeDepartamento;
		this.presupuestos = presupuestos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_departamento", unique = true, nullable = false)
	public Integer getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Integer idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "nombre_departamento", nullable = false, length = 70)
	public String getNombreDepartamento() {
		return this.nombreDepartamento;
	}

	public void setNombreDepartamento(String nombreDepartamento) {
		this.nombreDepartamento = nombreDepartamento;
	}

	@Column(name = "jefe_departamento", nullable = false, length = 100)
	public String getJefeDepartamento() {
		return this.jefeDepartamento;
	}

	public void setJefeDepartamento(String jefeDepartamento) {
		this.jefeDepartamento = jefeDepartamento;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "departamento")
	public List<Presupuesto> getPresupuestos() {
		return this.presupuestos;
	}

	public void setPresupuestos(List<Presupuesto> presupuestos) {
		this.presupuestos = presupuestos;
	}

}
