package com.ampersand.ebanca.Model;
// Generated Aug 21, 2020 8:50:12 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "mibanco")
public class Estado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idEstado;
	private String nombreEstado;
	private List<EstadoPresupuesto> estadoPresupuestos = new ArrayList<EstadoPresupuesto>(0);

	public Estado() {
	}

	public Estado(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}

	public Estado(String nombreEstado, List<EstadoPresupuesto> estadoPresupuestos) {
		this.nombreEstado = nombreEstado;
		this.estadoPresupuestos = estadoPresupuestos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estado", unique = true, nullable = false)
	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "nombre_estado", nullable = false, length = 20)
	public String getNombreEstado() {
		return this.nombreEstado;
	}

	public void setNombreEstado(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "estado")
	public List<EstadoPresupuesto> getEstadoPresupuestos() {
		return this.estadoPresupuestos;
	}

	public void setEstadoPresupuestos(List<EstadoPresupuesto> estadoPresupuestos) {
		this.estadoPresupuestos = estadoPresupuestos;
	}

}
