package com.ampersand.ebanca.Model;
// Generated Aug 21, 2020 8:50:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimientos generated by hbm2java
 */
@Entity
@Table(name = "movimientos", catalog = "mibanco")
public class Movimientos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idMovimiento;
	private Area area;
	private Banco banco;
	private String tipoMovimiento;
	private Date fecha;
	private Long saldo;

	public Movimientos() {
	}

	public Movimientos(Area area, Banco banco, String tipoMovimiento) {
		this.area = area;
		this.banco = banco;
		this.tipoMovimiento = tipoMovimiento;
	}

	public Movimientos(Area area, Banco banco, String tipoMovimiento, Date fecha, Long saldo) {
		this.area = area;
		this.banco = banco;
		this.tipoMovimiento = tipoMovimiento;
		this.fecha = fecha;
		this.saldo = saldo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_movimiento", unique = true, nullable = false)
	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_area", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_banco", nullable = false)
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Column(name = "tipo_movimiento", nullable = false, length = 20)
	public String getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(String tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "saldo", precision = 10, scale = 0)
	public Long getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Long saldo) {
		this.saldo = saldo;
	}

}
